// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZzanUrqpLVIjd2I_pfJOQVI3AzVCwNDs',
    appId: '1:937169410719:web:4eb03afbd8c728a5f0a0aa',
    messagingSenderId: '937169410719',
    projectId: 'pem-mob-ee806',
    authDomain: 'pem-mob-ee806.firebaseapp.com',
    storageBucket: 'pem-mob-ee806.firebasestorage.app',
    measurementId: 'G-GK9ZSZNX72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6n6kLmPckd1re3mOuLFysoFI-7QtSjYk',
    appId: '1:937169410719:android:b6d69c3758f49dbcf0a0aa',
    messagingSenderId: '937169410719',
    projectId: 'pem-mob-ee806',
    storageBucket: 'pem-mob-ee806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuzUlW7ts4ObwXZ8A9UKDCiHS5Fa4wkkY',
    appId: '1:937169410719:ios:606edeff1a76e9c1f0a0aa',
    messagingSenderId: '937169410719',
    projectId: 'pem-mob-ee806',
    storageBucket: 'pem-mob-ee806.firebasestorage.app',
    iosBundleId: 'com.example.pemrogramanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuzUlW7ts4ObwXZ8A9UKDCiHS5Fa4wkkY',
    appId: '1:937169410719:ios:606edeff1a76e9c1f0a0aa',
    messagingSenderId: '937169410719',
    projectId: 'pem-mob-ee806',
    storageBucket: 'pem-mob-ee806.firebasestorage.app',
    iosBundleId: 'com.example.pemrogramanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZzanUrqpLVIjd2I_pfJOQVI3AzVCwNDs',
    appId: '1:937169410719:web:6a112ffefa266263f0a0aa',
    messagingSenderId: '937169410719',
    projectId: 'pem-mob-ee806',
    authDomain: 'pem-mob-ee806.firebaseapp.com',
    storageBucket: 'pem-mob-ee806.firebasestorage.app',
    measurementId: 'G-WYD5EWVLNR',
  );
}
